title: XYBYTES
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://xybytes.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#baseurl: "/flexible-jekyll" 
#url: ""

# Author Settings
author: Christian Bortone # add your name
author-img: christian-bortone.jpg # add your photo
about-author: I am penetration tester and security researcher in my free time. I enjoy diving deep into Active Directory, Azure, and uncovering undocumented aspects of Microsoft technologies.
social-twitter: xybytes # add your Twitter handle
social-github: xybytes # add your Github handle
social-linkedin: christianbortone # add your Linkedin handle
social-email: christianbortone@gmail.com # add your Email address

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
